### ISSUE TITLE
allow dependencies installed using "dapp"

### ISSUE THREAD

**Issue by ghost** [BlockChainCompany/soljitsu#2]
Besides `npm` there is another tool to install smart contract dependencies called [`dapp`](https://dapp.readthedocs.io/en/latest/package_management.html#installing-packages). This tool uses git submodules for installing dependencies.

## Current Situation

There is no support for dependencies installed using `dapp`.

## Wanted Situation

Dependencies installed using `dapp` are picked up by `soljitsu`.

# NOTE

Implementing this feature depends on if this tool is used a lot or not

**Comment by rmi7** [comment]
doesn't seem relevant (anymore) since they mention in their docs that they will move to EthPM in "the near future"
