### ISSUE TITLE
allow dependencies installed using "EthPM"

### ISSUE THREAD

**Issue by ghost** [BlockChainCompany/soljitsu#3]
Besides `npm` there is another tool to install smart contract dependencies called [`EthPM`](https://www.ethpm.com/registry). This tool uses the Ethereum blockchain ⛓ to retrieve package versions and IPFS 🌍 for storage.

## Current Situation

There is no support for dependencies installed using `EthPM`.

## Wanted Situation

Dependencies installed using `EthPM` are picked up by `soljitsu`.

# NOTE

- `truffle` [already supports](http://truffleframework.com/docs/getting_started/packages-ethpm) `EthPM` dependencies
- `EthPM` currently lives on the Ropsten testnet

**Comment by rmi7** [comment]
in progress

**Comment by rmi7** [comment]
fixed in 13b0023
