### ISSUE TITLE
Extended import syntax and aliases

### ISSUE THREAD

**Issue by HarryR** [BlockChainCompany/soljitsu#4]
Hi,

 I frequently use the following pattern to make it easy to switch-out components:

```solidity
import {X as Y} from "./X.sol";
```

The code relies on `Y`, but the underlying implementation is `X`. The alias from `X` to `Y` doesn't work with your soljitsu flattening command at the moment.

Is this worth implementing?

**Comment by oneupalexander** [comment]
good point, I'll start working on it right away.

**Comment by oneupalexander** [comment]
fixed in PR #5

**Comment by oneupalexander** [comment]
@HarryR should work now

**Comment by oneupalexander** [comment]
updated version (`0.1.1`) and published to `npm`

**Comment by HarryR** [comment]
Thank you very much, I will provide some feedback later today or tomorrow. 👍

**Comment by HarryR** [comment]
I've avoided using aliases and the regex tweak works fine.
