### ISSUE TITLE
Package.json in standardtoken.sol?

### ISSUE THREAD

**Issue by meiremans** [BlockChainCompany/soljitsu#7]
when running soljitsu it errors beckause he is looking for zeppelin-solidity\contracts\token\ERC20\StandardToken.sol\package.json'. Why is Soljitsu looking for this package.json inside a sol file?

> $ soljitsu combine --src-dir=./contracts --dest-dir=./out --dep-dir=./node_modules
> fs.js:646
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                  ^
> 
> Error: ENOENT: no such file or directory, open 'C:\Users\nickm\IdeaProjects\horsecoin\contract\node_modules\zeppelin-solidity\contracts\token\ERC20\StandardToken.sol\package.json'
>     at Object.fs.openSync (fs.js:646:18)
>     at Object.fs.readFileSync (fs.js:551:33)
>     at getNodeModuleVersion (C:\Users\nickm\AppData\Roaming\npm\node_modules\soljitsu\lib\shared.js:91:17)
>     at depPaths.map (C:\Users\nickm\AppData\Roaming\npm\node_modules\soljitsu\lib\shared.js:300:26)
>     at Array.map (<anonymous>)
>     at getDepFiles (C:\Users\nickm\AppData\Roaming\npm\node_modules\soljitsu\lib\shared.js:285:12)
>     at retrieveNestedDeps (C:\Users\nickm\AppData\Roaming\npm\node_modules\soljitsu\lib\shared.js:331:26)
>     at combine (C:\Users\nickm\AppData\Roaming\npm\node_modules\soljitsu\lib\combine.js:266:28)
>     at Object.<anonymous> (C:\Users\nickm\AppData\Roaming\npm\node_modules\soljitsu\lib\index.js:91:21)
>     at Module._compile (module.js:635:30)

**Comment by rmi7** [comment]
Hi @meiremans, thanks for filing an issue, 

could you please provide the `import` statements at the top of the smart contract that errors?

**Comment by meiremans** [comment]
Yes: The import is in the Token contract:

> import 'zeppelin-solidity/contracts/token/ERC20/MintableToken.sol';

Anyhow if i remove this import. he starts doing the same on another file. My guess is that somehow package.json gets appended without the need to be.

>Error: ENOENT: no such file or directory, open 'C:\Users\nickm\IdeaProjects\horsecoin\contract\node_modules\zeppelin-solidity\contracts\math\SafeMath.sol\package.json'

**Comment by rmi7** [comment]
Thanks, I'm gonna investigate/fix it!

**Comment by rmi7** [comment]
fixed in #8

**Comment by rmi7** [comment]
The problem was that Windows uses backslash instead of forward slash and I wasn't correclty handling that, reproduced and than fixed it on a Windows 10 machine.

Also added tests, try `npm test`.

Published the new version on `npm` --> `0.1.3`.

please confirm the bug is fixed, then I will close this issue!

**Comment by meiremans** [comment]
Hello, confirmed!
Thank you very much!
